[package]
name = "seal"
version = "0.0.6-rc.1"
edition = "2024"

[dependencies]
# need to rely on the git version as it contains the most up-to-date luau;
# mlua creates official releases very infrequently but khvzak seems to be updating his `main` very regularly upon Luau releases.
# If this breaks we'll pin to a commit and risk lagging behind Luau
# but mlua's main branch is relatively stable and hasn't broken for us before nor for other projects.
# we need to enable error-send so we can propogate errors across threads in std_thread.rs
mlua = { git = "https://github.com/mluau/mluau.git", features = ["luau", "serialize", "error-send"] }
chrono = "0.4.38"
regex = "1.11.1"
# needed for seal setup (really useful!)
include_dir = { version = "0.7.4" }
# only decent non-tokio non-async simple http request lib
ureq = { version = "3.0.11", features = ["json", "rustls", "gzip"] }
# faster than std::mpsc, needed for @std/thread
crossbeam-channel = { version = "0.5.15" }
# serde_json blows up when reading jsonc so we use lenient instead
# feature "arbitrary_precision" causes headaches, we can just provide bigint/bigdecimal bindings instead
serde_json_lenient = { version = "0.2.4", features = ["preserve_order"] }
base64 = { version = "0.22.1" }
# serde_yaml is deprecated and unmaintained so we use serde_yml instead
serde_yml = "0.0.12"
toml = "0.5.9"
serde-xml-rs = "0.5.1"
copy_dir = "0.1.3"
# we should switch to a more maintained alternative when possible, 
# but as long as ring receives security updates it's not a huge priority
ring = "0.17.14"
rsa = "0.9.8"
rand = "0.8.5"
# simple wrapper lib, might want to switch to a more frequently updated one?
simple_crypt = "0.2.3"
hex = "0.4.3"
unicode-segmentation = "1.12.0"
# used for very fast string pattern searches (str.split)
aho-corasick = "1.1.3"
# necessary to loop over graphemes without storing the whole string into memory, 
# unicode-segmentation's iterators are literally allergic to being stored in a struct
unicode_reader = "1.0.2"
petname = { version = "2.0.2", features = ["default-rng", "default-words"] }

[profile.dev.package.num-bigint-dig]
opt-level = 3 # otherwise rsa keygen takes forever

[lints.clippy]
# reason: no autocomplete on inlined args + inconsistent syntax in macro (exprs not permitted); 
# better to be consistent in not using inlined format args, and if it's ridiculous, split it up or just write it in luau
uninlined_format_args = "allow"
